### ISSUE TITLE
TestInotifyOverflow fails on arm64

### ISSUE THREAD

**Issue by anthonyfok** [fsnotify/fsnotify#253]
### Which operating system (GOOS) and version are you using?

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux unstable (sid)
Release:	unstable
Codename:	sid
```

### Please describe the issue that occurred.

The Ubuntu Autopkgtest CI reveals that golang-fsnotify v1.4.7 has always failed at TestInotifyOverflow on arm64, but OK on all other tested architectures:

See:

* https://autopkgtest.ubuntu.com/packages/golang-fsnotify
* https://autopkgtest.ubuntu.com/packages/golang-fsnotify/cosmic/arm64

### Are you able to reproduce the issue? Please provide steps to reproduce and a code sample if possible.

I was able to reproduce this on my Raspberry Pi 3 running Debian arm64:

```
$ go get -v -u github.com/fsnotify/fsnotify
$ cd ~/go/src/github.com/fsnotify/fsnotify
$ go test -run TestInotifyOverflow -v ./...
=== RUN   TestInotifyOverflow
--- FAIL: TestInotifyOverflow (58.65s)
	inotify_test.go:422: Not done
FAIL
FAIL	github.com/fsnotify/fsnotify	58.671s
```

(Thinking out loud: I wonder if the test taking over 58 seconds is normal or not.  For comparison, the same test takes 6.01s on my amd64 laptop, 26.48s on armhf (Ubuntu Autopkgtest), 5.30s on ppc64el, 5.09s on s390x... oh, 25.04s on arm64 on Ubuntu Autopkgtest, which is on par with armhf... okay...)

**Comment by matthias-stone** [comment]
Hey Anthony! I think I fixed this as part of PR #265, can you verify that this is resolved for master for you?

**Comment by anthonyfok** [comment]
Thank you so much, Matthias!
I will find time test this out next week.  (Suddenly too many unexpected tasks landed in my lap past few days.)

**Comment by QuLogic** [comment]
I'm not sure that #265 fixes it everywhere. I saw that our package was failing on [aarch64](https://koji.fedoraproject.org/koji/taskinfo?taskID=32397520) and [s390x](https://koji.fedoraproject.org/koji/taskinfo?taskID=32397522), so I backported #265 and built again. Unfortunately, it still fails on [s390x](https://koji.fedoraproject.org/koji/taskinfo?taskID=32550683).

**Comment by QuLogic** [comment]
We've since updated from Go 1.12beta2 to the final 1.12, and it appears the failure on s390x is fixed now.

**Comment by matthias-stone** [comment]
@QuLogic Awesome! I'm going to mark this as closed, and if someone re-encounters a similar issue they can open a new bug.
